name: Build and Sign APKs & AAB

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create Google Services JSON File
      env: 
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json
      
    - name: Build Debug APK
      run: ./gradlew app:assembleDebug
    
    - name: Build Release APK
      run: ./gradlew app:assembleRelease
      
    - name: Build Release AAB
      run: ./gradlew app:bundleRelease

    - name: Sign Release APK
      uses: r0adkll/sign-android-release@v1
      id: sign_release_apk
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
        
    - name: Sign Debug APK
      uses: r0adkll/sign-android-release@v1
      id: sign_debug_apk
      with:
        releaseDirectory: app/build/outputs/apk/debug
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
    
    - name: Sign Release AAB
      uses: r0adkll/sign-android-release@v1
      id: sign_release_aab
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Create ZIP Archive of Signed Files
      run: |
        mkdir -p signed_files
        cp app/build/outputs/apk/release/*.apk signed_files/
        cp app/build/outputs/apk/debug/*.apk signed_files/
        cp app/build/outputs/bundle/release/*.aab signed_files/
        zip -r signed_artifacts.zip signed_files/
      
    - name: Upload Signed Artifacts ZIP
      uses: actions/upload-artifact@v4
      with:
        name: Signed Artifacts
        path: signed_artifacts.zip
